Fix config dir naming in tarball
Use xz over gz

diff --git a/pftiii/validation/validate b/pftiii/validation/validate
--- a/pftiii/validation/validate
+++ b/pftiii/validation/validate
@@ -1173,13 +1173,24 @@ merge_logs()
 	mv "${log}.sort" "${log}"
 }
 
+get_final_output_name()
+{
+	local name="pftiii_validation_"
+	if ! name+="$(get_organization_name)"; then
+		fail "Could not get organization name."
+	fi
+	name+="_"
+	if ! name+="$(get_lib_version)"; then
+		fail "Could not get library version."
+	fi
+
+	echo "${name}"
+}
+
 # Generate the name of the validation tarball.
 get_tarball_name()
 {
-	local name
-	name="pftiii_validation_$(get_organization_name)_"
-	name+="$(get_lib_version).tar.gz"
-	echo "${name}"
+	echo "$(get_final_output_name).tar.xz"
 }
 
 # Make a tarball of all libraries and logfiles to send to NIST.
@@ -1187,25 +1198,37 @@ make_tarball()
 {
 	echo -n "Creating validation submission... "
 
-	local tar_file
-	tar_file=$(get_tarball_name)
-	local new_name
-	new_name="${wd}/$(basename "$(get_tarball_name)" .tar.gz)"
-
-	mv "${output_dir}" "${new_name}"
-	cp -pr "${lib_dir}" "${new_name}"
-	cp -pr "${config_dir}" "${new_name}"
-
-	# NIST will build a fresh libpftiii.so
-	if ! rm "${new_name}/$(basename "${lib_dir}")/libpftiii.so"; then
-		local msg="An error occurred while copying libraries. Check "
-		msg+="file permissions."
-		fail "${msg}"
+	local final_output_name
+	if ! final_output_name="$(get_final_output_name)"; then
+		fail "Could not get final output name."
 	fi
-	if ! tar -C "${wd}" -c -z -f "${tar_file}" "$(basename "${new_name}")" \
-	    > /dev/null; then
-		fail "There was an issue creating the validation submission."
+	local final_output_path="${wd}/${final_output_name}"
+	local tar_file="${final_output_name}.tar.xz"
+
+	if ! mv -n "${output_dir}" "${final_output_path}" > /dev/null 2>&1; then
+		fail "Could not rename $(rp "${output_dir}")"
 	fi
+	if ! cp -pr "${local_lib_dir}" "${final_output_path}"; then
+		fail "Could not copy $(rp "${local_lib_dir}")"
+	fi
+	if ! cp -pr "${local_config_dir}" "${final_output_path}"; then
+		fail "Could not copy $(rp "${local_config_dir}")"
+	fi
+
+	# Remove unnecessary files
+	if ! find "${final_output_path}" \( -type f -name 'libpftiii.so' -o \
+	    -name 'README' \) -exec rm -f {} \;; then
+		fail "Could not remove unnecessary validation files"
+	fi
+
+	if ! tar -C "${wd}" -c -J -f "${tar_file}" "${final_output_name}" > \
+	    /dev/null 2>&1; then
+		fail "There was an issue creating the validation tar file."
+	fi
+
+	# Update globals
+	output_dir="$(dirname "${output_dir}")/$(get_final_output_name)"
+	driver_output_dir="${output_dir}/driver"
 
 	okay "${tar_file}"
 }
@@ -1263,7 +1286,7 @@ print_final_success()
 			box " -> ${v}" 80 '=' '|' 'l' 0 1
 		fi
 		line_num=$(( line_num + 1 ))
-	done < <(head -n 9 "${tar_file//.tar.gz/}/id.log" | tail -n 6)
+	done < <(head -n 9 "${tar_file//.tar.xz/}/id.log" | tail -n 6)
 	font_reset
 
 	echo
